apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  API_JWT_SECRET_KEY: "CHANGE_ME"
  API_TOKEN_ENCRYPTION_KEY: "CHANGE_ME"
  GITHUB_OAUTH_CLIENT_SECRET: "CHANGE_ME"
  OPENROUTER_API_KEY: "CHANGE_ME"
  GUARDRAILS_API_KEY: "CHANGE_ME"
