apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: brokers
  labels:
    strimzi.io/cluster: code-reviewer-kafka
spec:
  replicas: 3
  roles:
    - broker
  resources:
    requests:
      cpu: 500m
      memory: 1536Mi
    limits:
      cpu: "1"
      memory: 3Gi
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values: [stateful]
      tolerations:
        - key: workload
          operator: Equal
          value: stateful
          effect: NoSchedule
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
        class: gp3
