apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controllers
  labels:
    strimzi.io/cluster: code-reviewer-kafka
spec:
  replicas: 3
  roles:
    - controller
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values: [stateful]
      tolerations:
        - key: workload
          operator: Equal
          value: stateful
          effect: NoSchedule
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 3Gi
        deleteClaim: false
        class: gp3
