"""
    COH priority=high fixture: a class bundling unrelated concerns —
    user CRUD, email delivery, and report generation — each operating on
    its own data and serving a different purpose.
"""


class UserManager:
    def __init__(self) -> None:
        self._users: dict[str, dict] = {}
        self._smtp_host = "smtp.example.com"
        self._report_footer = "Generated by UserManager"

    def create_user(self, user_id: str, email: str) -> None:
        self._users[user_id] = {"email": email}

    def delete_user(self, user_id: str) -> None:
        del self._users[user_id]

    def send_welcome_email(self, user_id: str) -> None:
        email = self._users[user_id]["email"]
        print(f"connecting to {self._smtp_host} to email {email}")

    def send_password_reset_email(self, user_id: str) -> None:
        email = self._users[user_id]["email"]
        print(f"connecting to {self._smtp_host} to email {email}")

    def generate_signup_report(self) -> str:
        rows = "\n".join(self._users.keys())
        return f"{rows}\n{self._report_footer}"

    def generate_activity_report(self, user_id: str) -> str:
        return f"activity report for {user_id}\n{self._report_footer}"
